### PR TITLE
Add HIDPI variables and auto-scale feature for cheatsheet

### PR DESCRIPTION
**Pull request by jsl9208**
This PR adds some HIDPI variables and uses them to automatically scale down the cheatsheet, making it usable on scaled screens. Takes effect on Hyprland.

Solves https://github.com/end-4/dots-hyprland/issues/283. 

Tested 2880x1800, 2x scaled:
图片

1920x1080, 2x:
图片

### CODE REVIEW

**Comment by end-4** [comment]
this is really interesting... but why not have this for all windows? :thinking:

**Comment by jsl9208** [comment]
> this is really interesting... but why not have this for all windows? 🤔

Sorry I didn't understand the question. You mean other widges? Only the cheatsheet and overview window looks way much bigger after scaled IMO.

**Comment by jsl9208** [comment]
Fixing the issue with the overview window is simple. All that needs to be done is to change all occurrences of the variables such as SCREEN_* in its code to SCREEN_REAL_*. I am able to work on it after this merged.

**Comment by Mooling0602** [comment]
> Fixing the issue with the overview window is simple. All that needs to be done is to change all occurrences of the variables such as SCREEN_* in its code to SCREEN_REAL_*. I'd like to work on it later.

Hey bro, you may forgot to import { SCREEN_REAL_HEIGHT } in the `.config/ags/modules/cheatsheet/main.js`, so the change will be not complete. 
But I can't fix this, so I need your help to improve this.

**Comment by Mooling0602** [comment]
> Fixing the issue with the overview window is simple. All that needs to be done is to change all occurrences of the variables such as SCREEN_* in its code to SCREEN_REAL_*. I'd like to work on it later.

Hey bro, you may forgot to import { SCREEN_REAL_HEIGHT } in the `.config/ags/modules/cheatsheet/main.js`, so the change will be not complete. 
But I can't fix this, so I need your help to improve this.

**Pull request closed without merging**
