### PR TITLE
Fix #265

### LINKED ISSUE #265: [Issue]Three widgets seem to have encountered a problem
- **I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: EndeavourOS

---
## The issue

1. Both RAM usage and swap usage are constantly at 0%.
2. CPU usage is abnormally jumping around between 5% and 95%.

<details>
<summary>Click to expand</summary>

image

</details>

### PR DESCRIPTION
**Pull request by clsty**
Fix #265 by adding `LANG=C ` to fix locale.

### CODE REVIEW

**Comment by clsty** [comment]
Would you like to add me as collaborator here too?

I will:
- Maintain and improve the installation script thingy
  - I guess I'm already responsible for taking care of them ;)
- Other improvements that will not conflict with your work, e.g. small fixes that has been tested, typo, etc.

For other things I'll still just submit a PR or discuss with you first.

**Comment by clsty** [comment]
Would you like to add me as collaborator here too?

I will:
- Maintain and improve the installation script thingy
  - I guess I'm already responsible for taking care of them ;)
- Other improvements that will not conflict with your work, e.g. small fix that has been tested, typo, etc.

For other things I'll still just submit a PR or discuss with you first.

**Comment by end-4** [comment]
I haven't found a language that uses `,` for decimals to test so I never did this lol

**Comment by end-4** [comment]
About making you a collaborator, I think that's reasonable
- You're already taking care of the script and ironing out small stuff that I neglect, so just letting you write would be more convenient
- Big changes to ags stuff should go through a PR, yes
I'm going to add you now. Thank you for your dedication!

**Comment by clsty** [comment]
> I'm going to add you now. Thank you for your dedication!

As for dedication, it's same for you too :)
I especially appreciate you maintaining the AGS thingy ("sync ags"), as it often gets breaking changes lol

And thank you for such awesome configs. That's my best experience on Hyprland I've ever had.

**Pull request merged**
