### PR TITLE
On-Screen-Keyboard improvements

### PR DESCRIPTION
**Pull request by Motschen**
- Pressing shift will now cycle between shift, caps lock, and lowercase
- Visual representation of uppercase letters/symbols, as well as AltGr for German keyboards
  - You can also add the equivalent Alt keys for QWERTY keyboards, I just don't know what they'd be
- Added German QUERTZ virtual keyboard layout

### CODE REVIEW

**Comment by end-4** [comment]
cool

**Comment by end-4** [comment]
any idea for that empty capslock? :)

**Comment by Motschen** [comment]
> any idea for that empty capslock? :)

Maybe the left and right arrow keys?
That'd allow for easier navigation in texts.
Though idk if the position would be fitting.

**Comment by kxrur** [comment]
Is this supposed to work for the non-qwerty characters such as `ü`? 
ydotool types `[` when I click that key.

I am trying to add a cyrillic layout but am having a hard time making ydotool work with a different layout.

**Pull request merged**
