### PR TITLE
ags: implement per-monitor brightness control

### PR DESCRIPTION
**Pull request by MoetaYuko**
This implements per-monitor brightness control for **desktops** using [DDC/CI](https://wiki.archlinux.org/title/Backlight#External_monitors). I don't have a laptop to test the current brightnessctl approach, so a new user option is added to choose between brightnessctl and ddcutil.

Ideally, the supported controller for individual monitors should be auto-detected to make use-cases like built-in laptop display + external monitor work. Whoever can test this case may implement it in the future.

### CODE REVIEW

**Comment by end-4** [comment]
So ddcutil is just for external monitors right? Maybe we can do some guessing based on the monitor name to create ddcutil service for monitors that look like external ones and brightnessctl service for laptop one

My laptop screen is assigned the name `eDP-1`
Can you send your results of `hyprctl monitors -j`?

**Comment by MoetaYuko** [comment]
> So ddcutil is just for external monitors right? Maybe we can do some guessing based on the monitor name to create ddcutil service for monitors that look like external ones and brightnessctl service for laptop one

maybe, I'm unsure if determining from the name is robust enough.
> 
> My laptop screen is assigned the name `eDP-1` Can you send your results of `hyprctl monitors -j`?

```
[{
    "id": 0,
    "name": "DP-1",
    "description": "DOME imaging systems 273B1 demoset-1",
    "make": "DOME imaging systems",
    "model": "273B1",
    "serial": "demoset-1",
    "width": 3840,
    "height": 2160,
    "refreshRate": 59.98200,
    "x": 0,
    "y": 0,
    "activeWorkspace": {
        "id": 1,
        "name": "1"
    },
    "specialWorkspace": {
        "id": 0,
        "name": ""
    },
    "reserved": [0, 40, 0, 0],
    "scale": 2.00,
    "transform": 0,
    "focused": true,
    "dpmsStatus": true,
    "vrr": false,
    "activelyTearing": false,
    "disabled": false,
    "currentFormat": "XRGB8888",
    "availableModes": ["3840x2160@59.98Hz","1920x1200@59.98Hz","1920x1080@60.00Hz","1920x1080@60.00Hz","1920x1080@59.94Hz","1920x1080@50.00Hz","1600x1200@59.98Hz","1680x1050@59.98Hz","1400x1050@59.98Hz","1280x1024@60.02Hz","1440x900@59.89Hz","1280x960@60.00Hz","1280x800@59.98Hz","1280x720@60.00Hz","1280x720@60.00Hz","1280x720@59.94Hz","1280x720@50.00Hz","1024x768@60.00Hz","800x600@60.32Hz","720x480@60.00Hz","720x480@60.00Hz","720x480@59.94Hz","720x480@59.94Hz","640x480@60.00Hz","640x480@59.94Hz","640x480@59.94Hz"]
},{
    "id": 1,
    "name": "DP-2",
    "description": "Dell Inc. DELL E2417H 3KR5V78J1PYB",
    "make": "Dell Inc.",
    "model": "DELL E2417H",
    "serial": "3KR5V78J1PYB",
    "width": 1920,
    "height": 1080,
    "refreshRate": 60.00000,
    "x": 1920,
    "y": 0,
    "activeWorkspace": {
        "id": 10,
        "name": "10"
    },
    "specialWorkspace": {
        "id": 0,
        "name": ""
    },
    "reserved": [0, 40, 0, 0],
    "scale": 1.00,
    "transform": 0,
    "focused": false,
    "dpmsStatus": true,
    "vrr": false,
    "activelyTearing": false,
    "disabled": false,
    "currentFormat": "XRGB8888",
    "availableModes": ["1920x1080@60.00Hz","1680x1050@60.00Hz","1600x900@60.00Hz","1280x1024@75.03Hz","1280x1024@60.02Hz","1440x900@60.00Hz","1280x800@60.00Hz","1152x864@75.00Hz","1280x720@60.00Hz","1024x768@75.03Hz","1024x768@60.00Hz","800x600@75.00Hz","800x600@60.32Hz","640x480@75.00Hz","640x480@59.94Hz","720x400@70.08Hz"]
}]
```

```
╰─ ddcutil detect --brief
Display 1
   I2C bus:          /dev/i2c-5
   DRM connector:    card1-DP-1
   Monitor:          DMS:273B1:demoset-1

Display 2
   I2C bus:          /dev/i2c-6
   DRM connector:    card1-DP-2
   Monitor:          DEL:DELL E2417H:3KR5V78J1PYB
```

```
╰─ ddcutil detect
Display 1
   I2C bus:  /dev/i2c-5
   DRM connector:           card1-DP-1
   EDID synopsis:
      Mfg id:               DMS - DOME imaging systems
      Model:                273B1
      Product code:         9984  (0x2700)
      Serial number:        demoset-1
      Binary serial number: 0 (0x00000000)
      Manufacture year:     2022,  Week: 39
   VCP version:         2.2

Display 2
   I2C bus:  /dev/i2c-6
   DRM connector:           card1-DP-2
   EDID synopsis:
      Mfg id:               DEL - Dell Inc.
      Model:                DELL E2417H
      Product code:         41186  (0xa0e2)
      Serial number:        3KR5V78J1PYB
      Binary serial number: 827349314 (0x31505942)
      Manufacture year:     2017,  Week: 33
   VCP version:         2.1
```

**Comment by MoetaYuko** [comment]
btw according to [faq of ddcutil](https://www.ddcutil.com/faq/), some eDP panels may implement DDC/CI

**Comment by end-4** [comment]
the ddcutil service doesn't work for my eDP laptop screen. it just says `Unrecognized ddcutil command: 10`

**Comment by MoetaYuko** [comment]
> the ddcutil service doesn't work for my eDP laptop screen. it just says `Unrecognized ddcutil command: 10`

well this is normal. some eDP may implement ddc and others may not (your case), where brightnessctl should be used.

**Comment by end-4** [comment]
modified the config a bit and added guessing. does this work well for you?

**Comment by MoetaYuko** [comment]
> modified the config a bit and added guessing. does this work well for you?

Yes, 'auto' works for me and I'm okay with the current implementation.
A more robust detection approach might be: for each monitor, check if it's listed in `ddcutil detect` or `brightnessctl -l`, but this will impose additional difficulty which may not be worth it.

**Comment by end-4** [comment]
brightnessctl -l shows these, which i don't think is sufficient to detect that
image

**Comment by MoetaYuko** [comment]
updated the auto strategy to use `ddcutil` if a monitor appear in `ddcutil detect`, otherwise `brightnessctl`

**Pull request merged**
