### PR TITLE
booru: add save image

### PR DESCRIPTION
**Pull request by shinyPy**
save the image and put it in the folder based on the tag

### CODE REVIEW

**Comment by end-4** [comment]
it works :+1:
but nsfw stuff should be put in `homework/🌶️` folder

**Comment by end-4** [comment]
rating:q sometimes just contain stuff like bikini and sometimes contains nipples , so i'm putting it as nsfw

**Comment by shinyPy** [comment]
i dont add nsfw stuff since i dont use them, i was in the middle of adding it but you're faster lol.
thanks for the merge

**Comment by end-4** [comment]
wait i

**Comment by shinyPy** [comment]
whar

**Comment by end-4** [comment]
- changed join "_" to "+" because tags may have underscores
- i prefer not save stuff in folders with tags so i made it optional

**Comment by end-4** [comment]
okay now im done

**Comment by shinyPy** [comment]
No problem, thanks for the help!

**Pull request merged**
