### PR TITLE
Audio popups also showing up if the volume changes e.g. by keys

### PR DESCRIPTION
**Pull request by myryk31415**
The audio popup now works as in most setups and shows up if the volume changes. It does not if you skip a song etc.

I implemented it for backlight as well, but its not working. The hook doesn't trigger if I change the brightness via keybinds. I assume the service doesnt check for that? Didn't check yet.

### CODE REVIEW

**Comment by myryk31415** [comment]
One Issue: if you change to headphones, the popup appears because in most cases the volume is different

**Comment by myryk31415** [comment]
The popup now doesn't show up anymore if the device changes. Idk if there is a better way to check tho.

**Comment by myryk31415** [comment]
Should be ready if the feature is desired :)

**Comment by end-4** [comment]
lgtm <- (i often don't say this but i wanna say something different today)

**Comment by end-4** [comment]
anyway thanks, i can remove two keybinds now

**Comment by myryk31415** [comment]
Something didn't work out, for me the Panel now pops up when i pause music as well, I'm gonna have another look at it

**Comment by myryk31415** [comment]
Okay it only happens if you have volume levels over 100%.

(com.github.Aylur.ags:29989): GLib-GObject-CRITICAL **: 20:25:58.111: value "1.113281" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'

Any Ideas how to work around that?

**Comment by myryk31415** [comment]
Ah ofc its the progress bar. I'm working on it

**Pull request merged**
