### PR TITLE
Bugs resolved and new features added

### PR DESCRIPTION
**Pull request by xiadnoring**
Bugs resolved below:
- Problem with scrolling in chatgpt section
- Problem with friezes
- Problem with going beyond boundaries in the texts
- Problem with keyboard
- Problem with user config

New widgets added:
- Google Translater
- Power Profiles
- Random Wallpaper

New features added:
- Dynamically updated config
- Updating the application list when an application has been uninstalled/installed
- Custom user folder (~/.ags) (with custom hyprlock theme and other configs)
(Maybe we need to move user scripts and configs to a separate folder? )

https://github.com/user-attachments/assets/15461230-7729-461e-ad6b-99476bacf4f7

### CODE REVIEW

**Comment by s0mesh1t** [comment]
for some reason, the modules in the left panel broke down and the translator was not added

**Comment by xiadnoring** [comment]
maybe you need to create a config file in the following path: ~/.ags/config.json, which will be contains settings from the custom user_options. Can you say what happens with your left panel? (ags needs to be reloaded to bind the config file)

<details>
<summary>./.ags/config.json</summary>
<code>
<pre>
{
    "sidebar": {
	"pages": {
            "apis": {
                "order": ["gpt", "translater"]
            }
        },
        "translater": {
            "from": "auto",
            "to": "en",
            "languages": {
                "auto": "Auto",
                "en": "English",
                "fr": "French"
            }
        }
    },
    "bar": {
        "wallpaper_folder": "/home/XXX/Pictures/wallpapers/"
    },
    "animations": {
        "durationLarge": 200
    }
}
</pre>
</code>
</details>

**Comment by s0mesh1t** [comment]
> maybe you need to create a config file in the following path: ~/.ags/config.json, which will be contains settings from the custom user_options. Can you say what happens with your left panel? (ags needs to be reloaded to bind the config file)
> 
> ./.ags/config.json
> _not all settings can be dynamically updated_

Most likely, the lack of a file was the problem. 
My AI list didn't open (it was empty) I'll try again one of these days.

and everything else worked fine

**Comment by xiadnoring** [comment]
Have you configured the "sidebar"->"ai"->"extraGptModels" parameter?
<details>
<summary>
For example like this
</summary>
<code><pre>{
    "ai": {
        "defaultGPTProvider": "openrouter",
        "onSearch": "chatgpt"
    },
    "sidebar": {
        "ai": {
            "extraGptModels": {
                "openrouter": {
                    "name": "Llama 3 8B",
                    "logo_name": "openrouter-symbolic",
                    "description": "A unified interface for LLMs",
                    "base_url": "https://openrouter.ai/api/v1/chat/completions",
                    "key_get_url": "https://openrouter.ai/keys",
                    "key_file": "openrouter_key.txt",
                    "model": "meta-llama/llama-3-8b-instruct:free"
                }
            },
            "initMessages": [
                { "role": "user", "content": "hi" },
                { "role": "assistant", "content": "bye" }
            ]
        },
        "pages": {
            "apis": {
                "order": ["gpt", "translater"]
            }
        },
        "translater": {
            "from": "auto",
            "to": "en",
            "languages": {
                "auto": "Auto",
                "en": "English",
                "fr": "French"
            }
        }
    },
    "bar": {
        "wallpaper_folder": "/home/Timur/Pictures/wallpapers/"
    },
    "animations": {
        "durationLarge": 200
    }
}</pre></code>
</details>

**Comment by s0mesh1t** [comment]
image
yeah now it wokrs

why is the config file itself not in ~/.config/ags/? Why did it so far away?

**Comment by l4v3nx** [comment]
Can you implement a feature that enables certain power profile whenever laptop's external power is connected? (i.g. when battery is charging or charged - enable `performance` profile, when battery is discharging - enable `balanced` profile and when battery is low - enable `power-saver` profile) Thanks

**Comment by xiadnoring** [comment]
You can try to persuade @sh1zicus to implement that.

**Comment by l4v3nx** [comment]
@sh1zicus 🙏

**Comment by sh1zicus** [comment]
> @sh1zicus 🙏
I don't have a laptop, it will be difficult for me to make a working solution for this using ags (and do I even need to do this through ags?), it would be better to find this automatic switching on the Internet

**Comment by alr86** [comment]
Why this pull request was closed!? It's really useful

**Pull request closed without merging**
