### PR TITLE
Add config for swaylock

### PR DESCRIPTION
**Pull request by navidmafi**
Tried to follow colors and general themes used in illogical-impulse
image
image

### CODE REVIEW

**Comment by end-4** [comment]
- why is it so huge :skull:
- i'll merge if you 
  - decrease the font-size, indicator-radius and indicator-thickness
  - change the font to sans-serif (monospace is meant to be used in code and terminal and not to be abused everywhere)
  - have the background opaque and not use blur, since it's slow

- i'm still kinda unsatisfied since even swaylock-effects still looks very barebones, but oh well
- thanks for contributing

**Comment by navidmafi** [comment]
thanks for the feedback

> i'm still kinda unsatisfied since even swaylock-effects still looks very barebones

Yes, same here (for anyone reading this in the future: gtklock won't work utill some solution is found for #53 and swaylock is the most "correct" implementation of wayland session locking for now.)

**Comment by navidmafi** [comment]
I agree on blur being slow 
- making it fully opaque would compromise the looks 
- making it partially opaque would compromise the privacy 

I suggest that we should have blur enabled, but you decide.

**Comment by end-4** [comment]
well
i'm going to change that myself

**Pull request merged**
