### PR TITLE
fix show indicator pop on change brightness

### PR DESCRIPTION
**Pull request by riloraspopo**

### CODE REVIEW

**Comment by end-4** [comment]
in theory should work, but does it?

**Comment by end-4** [comment]
hmm
so this works if you make lines 11,12 this:
```ini
bindle = ,XF86MonBrightnessUp, exec, ags run-js 'brightness.screen_value += 0.05; indicator.popup(1);'
bindle = ,XF86MonBrightnessDown, exec, ags run-js 'brightness.screen_value -= 0.05; indicator.popup(1);'
```
can you remove the extra indicator popup lines?

**Comment by riloraspopo** [comment]
on my laptop, it works to make it just one line...

i remove extra indicator popup lines too (i comment it),

**Comment by end-4** [comment]
don't put ags run-js inside apostrophes of another 
ags run-js

**Comment by end-4** [comment]
oops misclick
but you should fix the wrapped `ags run-js`

**Comment by clsty** [comment]
Thank you for submitting the PR.

The `illogical-impulse` branch is merged to `main` branch, and will be deleted soon, see <https://github.com/end-4/dots-hyprland/pull/262> for more.

Please target this PR to the `main` branch instead.

Refer to <https://stackoverflow.com/questions/24159036/how-to-modify-a-pull-request-on-github-to-change-target-branch-to-merge-into> for instruction.

**Comment by daUnknownCoder** [comment]
hi @end-4 and @clsty, 
```bash
bindlr=, XF86MonBrightnessUp, exec, ags -r 'brightness.screen_value += 0.05; indicator.popup(2)'
bindle=, XF86MonBrightnessDown, exec, ags -r 'brightness.screen_value -= 0.05; indicator.popup(2)'
```

this one works more better, idk why but `indicator.popup(2)` works more better like any no. >1 makes it more responsive to presses

**Comment by end-4** [comment]
thanks for you suggestion of having both popup show and value setting in one keybind. though the popup(2) instead of 1 won't do anything
these are the final binds
```ini
bindle=, XF86MonBrightnessUp, exec, ags run-js 'brightness.screen_value += 0.05; indicator.popup(1);'
bindle=, XF86MonBrightnessDown, exec, ags run-js 'brightness.screen_value -= 0.05; indicator.popup(1);'
```

**Pull request closed without merging**
