### PR TITLE
Revamp installation with meta packages, and respect XDG dirs (#549)

### PR DESCRIPTION
**Pull request by Makrennel**
Supersedes #565

Made a bunch of changes to the installation process based on some things discussed in #549 which I think warranted making a new PR.

Now uses meta packages to install all needed packages.

User configured XDG directories now respected by install, update-dots and uninstall.

`uninstall.sh` should be somewhat more functional now (still wouldn't make any guarantees).

`install.sh` will attempt to set previously explicitly installed packages as being dependencies if rerun to allow orphaning if no longer part of what is declared in the meta packages.

Installation will still attempt to install dependencies as specified from a `dependencies.conf` file, but this should be kept to user-specific packages.

I've tested everything except `update-dots.sh`, but I can't say for sure that I've necessarily caught all potential problems.

### CODE REVIEW

**Comment by clsty** [comment]
Wow this one looks awesome. I'll look into it later.

**Comment by clsty** [comment]
It look fine to me. I'll be happy to merge it, but I've also noticed that you're making some minor improvements such as on code quality.

While I appreciate it a lot, I guess you may still find more to improve/fix as you gain more experience about the script.

So I suggest you to wait for a 3-days period, during which you make no more commits, which indicates that the codes seem stable enough.

But I'll let you decide. When you think it's ready to be merged, just tell me.

**Comment by Makrennel** [comment]
It should be fine to merge now. Any potential problems should have been sorted, and if I don't stop here I'll just nitpick endlessly. The stability from here can only really be gauged by people actually using it - I'm probably not going to be able to find any further problems by rerunning it again myself. I going to move on to trying to figure out a Nix flake, although that may take me some more time as I'm still learning Nix.

**Comment by Makrennel** [comment]
I say that... then I find another problem....

**Comment by clsty** [comment]
> It should be fine to merge now. Any potential problems should have been sorted, and if I don't stop here I'll just nitpick endlessly. The stability from here can only really be gauged by people actually using it - I'm probably not going to be able to find any further problems by rerunning it again myself. I going to move on to trying to figure out a Nix flake, although that may take me some more time as I'm still learning Nix.

That's a good point. I'll merge it now.
Thanks for your contribution!

**Pull request merged**
