### PR TITLE
Translation keybind using fuzzel

### PR DESCRIPTION
**Pull request by Nevrdid**
Alright, if some people may me interested by, here it is.
Script source : https://gist.github.com/Isti115/114b3a6ba953ec483a954499772ed5f8

### CODE REVIEW

**Comment by clsty** [comment]
We already have a AI sidebar which can do a great translation job, so maybe this one is redundant.
Thank you anyway.

Maybe have this one in Import Manually folder? I'll let @end-4 decide.

**Comment by end-4** [comment]
I don't like it, sorry
Having to type both languages and not being able to paste doesn't make it the best translator...

**Comment by end-4** [comment]
> We already have an AI sidebar which can do a great translation job, so maybe this one is redundant.

but you have to ask a question and it'll probably overkill

I already have the idea of adding a translation api to the sidebar in mind, but haven't got to it yet

**Comment by end-4** [comment]
> Maybe have this one in Import Manually folder? I'm not sure, and I'll let @end-4 decide

I don't like it, won't use this so I won't. Users can add it themselves

**Pull request closed without merging**
