### PR TITLE
Meaningful terminal colors and harmony 😌

### PR DESCRIPTION
**Pull request by midn8hustlr**
### Problem: 
1. The current terminal colors are dull and lack meaningful distinctions. Overuse of the accent color makes it hard to quickly differentiate file types (directories, executables, etc.).
2. Text visibility is poor, especially in light mode. Commands, executables, Git branches, and file sizes are hard to read.
3. Other minor issues, like the autocomplete suggestion blending with typed commands, further hinder usability.

<table>
  <tr>
    <th>Dark mode</th>
    <th>Light mode</th>
  </tr>
  <tr>
    <td>Image 1</td>
    <td>Image 2</td>
  </tr>
</table>

### Solution:
1. **Adopt popular, well-designed terminal [color schemes](https://gogh-co.github.io/Gogh/)**. But might not align with the theme accent ☹️.
2. **Avoid fully randomized color scheme generation** (like [pywal](https://github.com/dylanaraps/pywal)). It becomes difficult to recognize elements consistently (you have to pretty much relearn the scheme after changing theme).
3. **The ideal solution**: [Harmonize](https://m3.material.io/styles/color/advanced/adjust-existing-colors#1cc12e43-237b-45b9-8fe0-9a3549c1f61e) popular color schemes with accent colors derived from the wallpaper. Thanks to [materialyoucolor-python](https://github.com/T-Dynamos/materialyoucolor-python). This creates a visually pleasing and functional experience.

### EyeCandy 😋
image
image
image
image
image

### Configuration 🤓
1. Choose between multiple colorschemes in `colorgen.sh` (or add custom schemes in `~/.config/ags/scripts/templates/terminal`)

<table>
  <tr>
    <th>Catppuccin</th>
    <th>VS Code</th>
    <th>Gruvbox</th>
  </tr>
  <tr>
    <td>Image 1</td>
    <td>Image 2</td>
    <td>Image 2</td>
  </tr>
</table>

2. Control how much to blend with accent (make it more boring). Use `harmony` as a multiplier for hue shift. To preserve the semantic meaning of static colors (such as a red to communicate errors), `threshold`  limits the amount that a color’s hue can change. Harmonized colors will become warmer or cooler in hue without appearing like another type of color.

<table>
  <tr>
    <th>Conservative</th>
    <th>Moderate</th>
    <th>Liberal</th>
  </tr>
  <tr>
    <td>harmony: 0.5 <br> threshold: 15 <br> blend_bg_fg: False </td>
    <td>harmony: 0.5 <br> threshold: 35 <br> blend_bg_fg: True </td>
    <td>harmony: 0.9 <br> threshold: 180 <br> blend_bg_fg: True </td>
  </tr>
  <tr>
    <td>Image 1</td>
    <td>Image 2</td>
    <td>Image 2</td>
  </tr>
</table>

I would welcome your thoughts and suggestions on this.

### CODE REVIEW

**Comment by end-4** [comment]
Very cool. I've been busy...
Somehow when I test this I'm finally can reproduce #399. I'll have to see what's causing it

**Comment by end-4** [comment]
I'm getting `generate_colors_material.py: error: unrecognized arguments: True` from the python script

**Comment by end-4** [comment]
Fixed
Thanks for your contribution!

**Comment by end-4** [comment]
may i have the miku wall 👉👈

**Comment by midn8hustlr** [comment]
Sure 
wallpaperflare com_wallpaper

**Pull request merged**
