### PR TITLE
Illogical impulse

### PR DESCRIPTION
**Pull request by samvictordr**
Added really basic error handling to the shell script, and edited it to clear the terminal it's running on after every stage of the install.

### CODE REVIEW

**Comment by end-4** [comment]
Let's not `clear` after every step. 
In case the user changes their mind and wants to go back, they can scroll up and see what changes were made so they can revert them easily

**Comment by samvictordr** [comment]
In that case, I could add a switch to the script that allows reverting (removing all dependencies of hypr along with hyprland) so the user doesn't have to go through the process of finding and removing all the dependencies themselves

**Review by end-4 — APPROVED** [review]
alright

**Comment by end-4** [comment]
> In that case, I could add a switch to the script that allows reverting (removing all dependencies of hypr along with hyprland) so the user doesn't have to go through the process of finding and removing all the dependencies themselves

i guess an `uninstall.sh` would be nice

**Comment by sanhariharan** [comment]
HYPRLAND IS AWESOME

**Comment by end-4** [comment]
it's not awesome it's hyprland

**Pull request merged**
